--liquibase formatted sql

--changeset Andrii:create-actors-table

CREATE TABLE actors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),

    country_id BIGINT,

    CONSTRAINT fk_actor_country
        FOREIGN KEY (country_id)
            REFERENCES countries (id)
);
